version: '3.8'
services:
  backend:
    image: sanctuary-fitness-backend
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./backend:/src
      - /src/node_modules
    environment:
      DB_PASSWORD: 'postgres'
      DB_USER: 'postgres'
      DB_NAME: 'postgres'
      DB_PORT: 5432
      DB_HOST: 'db'
      NODE_ENV: 'production'
      SERVER: http://localhost:8080
      SERVER_PORT: 8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run build-start'

  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    image: sanctuary-fitness-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/src
      - /src/node_modules
    stdin_open: true
    command: 'npm run build-start'

volumes:
  postgres-data:
