version: '3.8'
services:
  api:
    image: api
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DB_PASSWORD: 'postgres'
      DB_USER: 'postgres'
      DB_NAME: 'postgres'
      DB_PORT: 5432
      DB_HOST: 'db'
      NODE_ENV: 'development'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run dev'

  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    image: app
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: 'npm run dev'

volumes:
  postgres-data:
